# Generated by Django 4.2 on 2023-06-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('dias_de_trabajo', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_marcacion', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=7)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
            ],
        ),
    ]
